---
groups:
  - group_name: oracle_group
    servers:
      - name: oracle
        type: slave
        box: centos/7
        memory: 512
        ip: 10.0.20.20
        synced_folders: 
          - { guest: "./server", host: "/home/vagrant/server" }
        forwarded_ports:
          - { guest: 1521, host: 1521 }
  - group_name: activemq_group
    servers:
      - name: activemq
        type: slave
        box: centos/7
        memory: 512
        ip: 10.0.20.30
        synced_folders: 
          - { guest: "./server", host: "/home/vagrant/server" }
        forwarded_ports:
          - { guest: 61616, host: 8616 }
          - { guest: 8161, host: 8161 }
  - group_name: management_server 
    servers:
      - name: mgmt
        type: master
        box: centos/7
        memory: 256
        ip: 10.0.20.10
        synced_folders: 
          - { guest: "./server", host: "/home/vagrant/server" }
        forwarded_ports: